version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rating_db
    ports:
      - "5432:5432"
    volumes:
      - rating_data:/var/lib/postgresql/data

volumes:
  rating_data: