# Generated by Django 6.0.3 on 2026-03-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('result_score', models.FloatField()),
                ('work_score', models.FloatField()),
                ('people_score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region_score', to='regions.region')),
            ],
            options={
                'verbose_name': 'Оценка региона',
                'verbose_name_plural': 'Оценки регионов',
            },
        ),
    ]
