# Generated by Django 6.0.3 on 2026-03-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
        ('rating', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionIndicatorScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators_region_scores', to='indicators.indicator')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions_indicator_scores', to='regions.region')),
            ],
        ),
    ]
