# Generated by Django 6.0.3 on 2026-03-28 07:31

from django.db import migrations


def rename_tables_if_needed(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())

    rename_pairs = [
        ("rating_regionindicatorscore", "region_indicator_scores"),
        ("rating_regionscore", "region_scores"),
    ]

    for old_name, new_name in rename_pairs:
        if old_name in existing_tables and new_name not in existing_tables:
            old_quoted = schema_editor.quote_name(old_name)
            new_quoted = schema_editor.quote_name(new_name)
            schema_editor.execute(f"ALTER TABLE {old_quoted} RENAME TO {new_quoted}")
            existing_tables.discard(old_name)
            existing_tables.add(new_name)


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicator_label_alter_indicatorcategory_label_and_more'),
        ('rating', '0002_regionindicatorscore'),
        ('regions', '0002_alter_akim_table_alter_region_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionindicatorscore',
            options={'verbose_name': 'Оценка по показателю', 'verbose_name_plural': 'Оценки по показателям'},
        ),
        migrations.AlterUniqueTogether(
            name='regionindicatorscore',
            unique_together={('region', 'indicator')},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_tables_if_needed, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='regionindicatorscore',
                    table='region_indicator_scores',
                ),
                migrations.AlterModelTable(
                    name='regionscore',
                    table='region_scores',
                ),
            ],
        ),
    ]
