# Generated by Django 6.0.3 on 2026-03-28 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_regionindicatorscore_options_and_more'),
        ('regions', '0003_region_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionScoreType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='regionscore',
            options={'verbose_name': 'Оценка по показателю', 'verbose_name_plural': 'Оценки по показателям'},
        ),
        migrations.AddField(
            model_name='regionscore',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regionscore',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='regionscore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='regionscore',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions_indicator_scores', to='regions.region'),
        ),
        migrations.AlterModelTable(
            name='regionscore',
            table='region_scores',
        ),
        migrations.AddField(
            model_name='regionscore',
            name='score_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rating.regionscoretype'),
        ),
        migrations.AlterUniqueTogether(
            name='regionscore',
            unique_together={('region', 'score_type', 'object_id')},
        ),
        migrations.DeleteModel(
            name='RegionIndicatorScore',
        ),
        migrations.RemoveField(
            model_name='regionscore',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='regionscore',
            name='people_score',
        ),
        migrations.RemoveField(
            model_name='regionscore',
            name='result_score',
        ),
        migrations.RemoveField(
            model_name='regionscore',
            name='work_score',
        ),
    ]
