# Generated by Django 6.0.3 on 2026-03-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_regionscoretype_alter_regionscore_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionscoretype',
            options={'verbose_name': 'Тип оценки', 'verbose_name_plural': 'Типы оценок'},
        ),
        migrations.AlterModelTable(
            name='regionscore',
            table='region_scores',
        ),
        migrations.AlterModelTable(
            name='regionscoretype',
            table='region_score_types',
        ),
    ]
