# Generated by Django 6.0.3 on 2026-03-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('small_description', models.TextField(blank=True, null=True)),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('influence_level', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('high_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('root_system_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
                'db_table': 'indicators',
            },
        ),
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.TextField()),
                ('system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Категория показателей',
                'verbose_name_plural': 'Категории показателей',
                'db_table': 'indicator_categories',
            },
        ),
        migrations.CreateModel(
            name='IndicatorSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.TextField()),
                ('system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Сектор показателей',
                'verbose_name_plural': 'Сектора показателей',
                'db_table': 'indicator_segments',
            },
        ),
        migrations.CreateModel(
            name='IndicatorPriority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_number', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_entries', to='indicators.indicator')),
            ],
            options={
                'verbose_name': 'Приоритет показателя',
                'verbose_name_plural': 'Приоритеты показателей',
                'db_table': 'indicator_priorities',
            },
        ),
        migrations.CreateModel(
            name='IndicatorScope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.TextField()),
                ('system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scopes', to='indicators.indicatorcategory')),
            ],
            options={
                'verbose_name': 'Сфера показателей',
                'verbose_name_plural': 'Сферы показателей',
                'db_table': 'indicator_scopes',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='scope_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.indicatorscope'),
        ),
        migrations.AddField(
            model_name='indicatorcategory',
            name='segment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='indicators.indicatorsegment'),
        ),
    ]
