# Generated by Django 6.0.3 on 2026-03-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indicatorcategory',
            name='label',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='indicatorscope',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indicatorsegment',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
