# Generated by Django 6.0.3 on 2026-03-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicator_label_alter_indicatorcategory_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='scope_id',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='indicatorcategory',
            old_name='segment_id',
            new_name='segment',
        ),
        migrations.RenameField(
            model_name='indicatorscope',
            old_name='category_id',
            new_name='category',
        ),
    ]
