# Generated by Django 6.0.3 on 2026-03-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_rename_scope_id_indicator_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorsegment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
