# Generated by Django 6.0.3 on 2026-03-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isCity', models.BooleanField(default=False)),
                ('population', models.IntegerField()),
                ('kato', models.CharField(max_length=50)),
                ('sdu_name', models.CharField(max_length=100)),
                ('sdu_second_name', models.CharField(max_length=100)),
                ('sdu_third_name', models.CharField(max_length=100)),
                ('sdu_fourth_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Akim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='akims_photos/')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.region')),
            ],
            options={
                'verbose_name': 'Аким',
                'verbose_name_plural': 'Акимы',
            },
        ),
    ]
