# Generated by Django 6.0.3 on 2026-03-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akim',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='akim',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
