# Generated by Django 6.0.3 on 2026-03-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_create_at_akim_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='sdu_fourth_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='sdu_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='sdu_second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='sdu_third_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
