# Generated by Django 6.0.3 on 2026-03-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_region_sdu_fourth_name_alter_region_sdu_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Akim',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
