# Generated by Django 6.0.3 on 2026-03-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='akim',
            table='akims',
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
    ]
