# Generated by Django 6.0.3 on 2026-03-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_akim_table_alter_region_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
