# Generated by Django 6.0.3 on 2026-03-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_region_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
